<?
$PERM["en"]["8"]="X";
$PERM["en"]["7"]="X";
$PERM["team"]["7"]="X";
$PERM["sale"]["7"]="X";
$PERM["rbs.payment"]["7"]="X";
$PERM["personal"]["7"]="X";
$PERM["payinfo"]["7"]="X";
$PERM["orders"]["7"]="X";
$PERM["news"]["7"]="X";
$PERM["local"]["7"]="X";
$PERM["gallery"]["7"]="X";
$PERM["faq"]["7"]="X";
$PERM["equipment"]["7"]="X";
$PERM["corporate"]["7"]="X";
$PERM["contacts"]["7"]="X";
$PERM["cgi-bin"]["7"]="X";
$PERM["certificate"]["7"]="X";
$PERM["cabinet"]["7"]="X";
$PERM["about"]["7"]="X";
$PERM["/"]["*"]="R";
$PERM["/en/"]["*"]="R";
?>